# Generated by Django 5.0.6 on 2024-10-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_knowledge', models.CharField(choices=[('none', 'No prior knowledge'), ('basic', 'Basic understanding of computers'), ('intermediate', 'Intermediate knowledge (e.g., programming basics)'), ('advanced', 'Advanced knowledge (e.g., software development, networking)')], max_length=100)),
                ('speciality_target', models.CharField(choices=[('it', 'Information Technology'), ('engineering', 'Engineering'), ('science', 'Science (e.g., Physics, Chemistry)'), ('mathematics', 'Mathematics'), ('business', 'Business/Management'), ('arts', 'Arts/Humanities'), ('education', 'Education'), ('healthcare', 'Healthcare/Medicine'), ('law', 'Law'), ('social_sciences', 'Social Sciences'), ('high_school', 'High School Student'), ('other', 'Other')], max_length=100)),
                ('learn_target', models.CharField(choices=[('build_apps', 'Build applications'), ('data_analysis', 'Data Analysis'), ('automate_tasks', 'Automate tasks'), ('secure_systems', 'Secure systems'), ('develop_websites', 'Develop websites'), ('learn_programming', 'Learn programming languages'), ('manage_projects', 'Manage IT projects'), ('transition_careers', 'Transition to an IT career'), ('other', 'Other')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Step2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=100)),
                ('age', models.IntegerField()),
                ('tell_us_about_yourself', models.CharField(max_length=200)),
            ],
        ),
    ]
